(import (rnrs base)
        (rnrs io simple)
        (rnrs control)
        (rnrs programs)
        (qk6 json)
        (qk6 test))

(test-begin "json")
(define string/string "\"hello, world!\"")
(define number/string "42")
(define empty-object/string "{}")
(define object-1/string "{\"msg\":\"say \\\"hello, world!\\\"\"}")
(define object-3/string "{\"a\":true,\"b\":false,\"c\":null}")
(define nested-object/string "{\"a\": {\"b\": {\"c\": {}}, \"B\": true}, \"A\":42}")
(define normalized-nested-object/string "{\"a\":{\"b\":{\"c\":{}},\"B\":true},\"A\":42}")
(define empty-array/string "[]")
(define empty-array-1/string "[ ]")
(define array-1/string "[\"hello\"]")
(define array-3/string "[42, 42.0, false]")
(define normalized-array-3/string "[42,42.0,false]")
(define nested-array/string "[[],\r[[[]],\n[\"a\", \"b\"]]]")
(define normalized-nested-array/string "[[],[[[]],[\"a\",\"b\"]]]")

(define string/json "hello, world!")
(define number/json 42)
(define empty-object/json '())
(define object-1/json '(("msg" . "say \\\"hello, world!\\\"")))
(define object-3/json '(("a" . #t) ("b" . #f) ("c" . null)))
(define nested-object/json '(("a" . (("b" . (("c" . ())))
                                     ("B" . #t)))
                             ("A" . 42)))
(define empty-array/json '#())
(define array-1/json '#("hello"))
(define array-3/json '#(42 42.0 #f))
(define nested-array/json '#(#() #(#(#()) #("a" "b"))))

(test-equal (string->json string/string) string/json)
(test-equal (string->json number/string) number/json)
(test-equal (string->json empty-object/string) empty-object/json)
(test-equal (string->json object-1/string) object-1/json)
(test-equal (string->json object-3/string) object-3/json)
(test-equal (string->json nested-object/string) nested-object/json)
(test-equal (string->json empty-array/string) empty-array/json)
(test-equal (string->json empty-array-1/string) empty-array/json)
(test-equal (string->json array-1/string) array-1/json)
(test-equal (string->json array-3/string) array-3/json)
(test-equal (string->json nested-array/string) nested-array/json)

(test-equal (json->string string/json) string/string)
(test-equal (json->string number/json) number/string)
(test-equal (json->string empty-object/json) empty-object/string)
(test-equal (json->string object-1/json) object-1/string)
(test-equal (json->string object-3/json) object-3/string)
(test-equal (json->string nested-object/json) normalized-nested-object/string)
(test-equal (json->string empty-array/json) empty-array/string)
(test-equal (json->string array-1/json) array-1/string)
(test-equal (json->string array-3/json) normalized-array-3/string)
(test-equal (json->string nested-array/json) normalized-nested-array/string)
(test-end "json")
